name: Deploy on Push

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Make HTTP request to deployment script
        run: curl -X GET https://webiflysolutions.com/webhook/index.php
